### ISSUE TITLE
你好，我用你的组件运行时提示undefined this.unlisten()

### ISSUE THREAD

**Issue by happyEgg** [xiaobuu/react-native-amap-location#1]

**Comment by tyao1** [comment]
你好，能贴一下你的代码不，我帮你看看。
this.unlisten 是做例子用到的一个变量，可以自行调整。

**Comment by happyEgg** [comment]
this.unlisten();我按照你的例子写的，但是不知道你的这个函数是怎么实现的，所以能贴一下代码吗？谢谢

**Comment by tyao1** [comment]
https://github.com/xiaobuu/react-native-amap-location/blob/master/index.js

**Comment by tyao1** [comment]
@happyEgg 可以贴一下你的代码我帮你看看

**Comment by tyao1** [comment]
如有问题，欢迎继续open这个issue

**Comment by mvpdream** [comment]
@happyEgg 你的问题解决了吗

**Comment by happyEgg** [comment]
@mvpdream 我没有用这个组件

**Comment by tyao1** [comment]
@mvpdream 加我qq 294577811把

**Comment by mvpdream** [comment]
@xiaobuu 加了 坐等回复

**Comment by tyao1** [comment]
确实有问题，listener被垃圾回收了，导致undefined。。 欢迎提交pr
