### ISSUE TITLE
运行出错了

### ISSUE THREAD

**Issue by mvpdream** [xiaobuu/react-native-amap-location#5]
![image](https://cloud.githubusercontent.com/assets/16203724/16513928/1a472a0c-3f9b-11e6-8d3e-8c2c2490f4c0.png)

**Comment by songyouwei** [comment]
@mvpdream 我也碰到了这个问题，是什么原因？

**Comment by mvpdream** [comment]
@songyouwei 重新run一下

**Comment by waynexu110** [comment]
请问
undefined is not an object (evaluating 'AMapLocation.startLocation')
这个问题解决没有？

我的环境是
react-native 0.39.2
android 4.4

我重新react-native run-android了不行
然后把原来安装的app卸载再运行也不行！
求助！
